start: statement+

statement: activation "."
         | inhibition "."
         | knockout "."
         | binding "."

activation: gene "activates" gene  -> activation
inhibition: gene "inhibits" gene  -> inhibition
knockout: gene "knockout" "inhibits" gene  -> knockout
        | gene "knockout" "leads to" gene  -> knockout
binding: gene "binds" gene -> binding

gene: CNAME
process: CNAME

%import common.CNAME
%import common.WS
%ignore WS
