start: statement+

statement: activation "."
        | inhibition "."
        | knockout "."
        | binding "."

activation: gene "activates" gene   -> activation
inhibition: gene "inhibits" gene    -> inhibition
knockout:   gene "knockout" "inhibits" gene  -> knockout
        | gene "knockout" "leads to" gene  -> knockout
binding:    gene "binds" gene       -> binding

// terminals
GENE: /[A-Za-z][A-Za-z0-9-]*/
%import common.WS
%ignore WS

gene: GENE
